sistema_consulta/urls.py
from django.conf.urls import include, url
from django.contrib import admin

#urlpatterns = patterns('',
#
#   url(r'^admin/', include(admin.site.urls)),
#
#   url(r'^topologia/',
#   include('apps.topologia.urls')
#                           ),
#                       # PARA AGREGAR LA AUTENTICACION DEL USUARIO
## url(r'^api-auth/',
       # include('rest_framework.urls', namespace='rest_framework')),
#                       url(r'^chaining/',
#                           include('pixelfields_smart_selects.urls')
#                           ),
#
#                       #url(r'^estado/',
#                       #    include('apps.topologia.estados.urls')
#                       #    ),
#
#                       )

urlpatterns = [
    url(r'^administrador/', include(admin.site.urls)),
    url(r'^api/', include('apps.topologia.urls')),
    url(r'^api/', include('apps.centro_votacion.urls')),
    url(r'^', include('apps.registro.urls')),
    # PARA AGREGAR LA AUTENTICACION DEL USUARIO
    #url(r'^api-auth/',
    #    include('rest_framework.urls', namespace='rest_framework')),
    url(r'^chaining/', include('pixelfields_smart_selects.urls')),

    url(r'^estado/', include('apps.topologia.estados.urls')),
    url(r'^', include('apps.topologia.estados.urls')),
    url(r'^municipio/', include('apps.topologia.municipios.urls')),
    url(r'^parroquia/', include('apps.topologia.parroquias.urls')),
    url(r'^centro_votacion/', include('apps.centro_votacion.urls')), # Url para centro de votacion
    url(r'^registro_electoral/', include('apps.registro.urls')), # Url para centro de votacion
    url(r'^iniciar/', include('apps.login.urls')),
]

apps/registro/models.py
# -*- encoding: utf-8 -*-
from django.db import models
#from smart_selects.db_fields import ChainedForeignKey
from smart_selects.db_fields import ChainedForeignKey
from django.core.urlresolvers import reverse
from apps.topologia.estados.models import Estado
from apps.topologia.municipios.models import Municipio
from apps.topologia.parroquias.models import Parroquia
from apps.centro_votacion.models import CentroVotacion
import datetime
from django.contrib.humanize.templatetags.humanize import naturalday, naturaltime

# Create your models here.
NACIONALIDAD = (
    ('V', 'Venezolano'),
    ('E', 'Extranjero'),
)

SEXO = (
    ('M', 'Masculino'),
    ('F', 'Femenino'),
)

class RegistroElectoral(models.Model):
    
    nac = models.CharField(verbose_name="Nacionalidad", max_length=1, choices=NACIONALIDAD, default='V')
    cedula = models.CharField(verbose_name="Cédula", max_length=8, unique=True, null=True)
    p_apellido = models.CharField(verbose_name="Primer Apellido", max_length=200, null=True)
    s_apellido = models.CharField(verbose_name="Segundo Apellido", max_length=200, null=True)
    p_nombre = models.CharField(verbose_name="Primer Nombre", max_length=200, null=True)
    s_nombre = models.CharField(verbose_name="Segundo Nombre", max_length=200, null=True)
    f_nac = models.DateField('Fecha de nacimiento', null=True)
    sexo = models.CharField(verbose_name="Sexo", max_length=1, choices=SEXO, null=True)
    cod_estado = models.ForeignKey(Estado, to_field='cod_estado', on_delete=models.SET_NULL, related_name='estado_registro', null=True)
    cod_municipio = models.ForeignKey(Municipio)
    cod_parroquia = models.ForeignKey(Parroquia)
    cod_nuevo = models.ForeignKey(CentroVotacion, to_field='cod_n', on_delete=models.SET_NULL, related_name='centro_registro', null=True)
    cod_viejo = models.CharField(verbose_name="Código anterior", max_length=20, null=True)
    date_create = models.DateTimeField(auto_now_add=True, auto_now=False, null=True)
    date_update = models.DateTimeField(auto_now_add=False, auto_now=True, null=True)
    user = models.CharField(max_length=15, null=True)
    mun = models.CharField(max_length=30, null=True)



    def __unicode__(self):
        # Método para retornar por defecto el valor de un campo especificado
        return self.cedula

templates/registroElectoral/borrar_elector.html
{% extends "base/base.html" %} <!-- Heredando (Bloque) plantilla index -->
    {% block title %}Eliminar Elector{% endblock %} <!--Bloque para definir el título-->
    
    {% block contenido %} <!-- Apertura de la carga de datos en el bloque 'contenido' de la plantilla 'base' -->
    <form method="post">{% csrf_token %}
        <!--Ambas formas de mostrar datos del modelo son validas-->
        ¿ Esta seguro que desea eliminar el registro "{{ object.p_nombre }} {{ eliminar_elector.p_apellido }}"?
        <input type="submit" value="Eliminar" />
    </form>
    {% endblock contenido%} <!-- Cierre de la carga de datos en el bloque 'contenido' de la plantilla 'base' -->

templates/registroElectoral/edit_elector.html
{% extends "base/base.html" %} <!-- Heredando (Bloque) plantilla index -->

{% block title %}Editar Electores{% endblock title%} <!--Bloque para definir el título-->

{% block contenido %} <!-- Apertura de la carga de datos en el bloque 'contenido' de la plantilla 'base' -->
<body>
    <h1>Editar Electores</h1>
    <form method="post">
	{% csrf_token %}
	<table style="text-align:center;">
	    <tr>
		<td colspan="2" style='background-color: #D9EDF7'>
		    Editar elector
		</td>
	    </tr>
	    <tr>
		<td>Nacionalidad:</td>
		<td>
		    <!--<input type='text' required id="id_nac" name="nac" value='{{obj_regelector.nac}}'/>-->
		    <select type='text' required id="id_nac" name="nac" style='width:200px;'>
			{% if obj_regelector.nac == 'V' %}
			    <option value='V' selected='selected'>Venezolano</option>
			{% endif %}
			{% if not obj_regelector.nac == 'V' %}
			    <option value='V'>Venezolano</option>
			{% endif %}
			{% if obj_regelector.nac == 'E' %}
			    <option value='E' selected='selected'>Extranjero</option>
			{% endif %}
			{% if not obj_regelector.nac == 'E' %}
			    <option value='E'>Extranjero</option>
			{% endif %}
		    </select>
		</td>
	    </tr>
	    <tr>
		<td>Cédula:</td>
		<td><input id="id_cedula" class="hola" required maxlength="50" name="cedula" type="text" value='{{obj_regelector.cedula}}'/>
		</td>
	    </tr>
	    <tr>
		<td>Primer Apellido:</td>
		<td><input type='text'  id="id_p_apellido" name="p_apellido" value='{{obj_regelector.p_apellido}}'/></td>
	    </tr>
	    <tr>
		<td>Segundo Apellido:</td>
		<td><input type='text'  id="id_s_apellido" name="s_apellido" value='{{obj_regelector.s_apellido}}'/></td>
	    </tr>
	    <tr>
		<td>Primer Nombre:</td>
		<td><input type='text'  id="id_p_nombre" name="p_nombre" value='{{obj_regelector.p_nombre}}'/></td>
	    </tr>
	    <tr>
		<td>Segundo Nombre:</td>
		<td><input type='text'  id="id_s_nombre" name="s_nombre" value='{{obj_regelector.s_nombre}}'/></td>
	    </tr>
	    <tr>
		<td>Fecha de Nacimiento:</td>
		<td><input type='text' required id="datepicker" name="f_nac" value='{{f_nac}}'/></td>
	    </tr>
	    <tr>
		<td>Sexo:</td>
		<td>
		    <!--<input type='text' required id="id_sexo" name="sexo" value='{{obj_regelector.sexo}}'/>-->
		    <select required id="id_sexo" name="sexo" style='width:200px;'>
			{% if obj_regelector.sexo == 0 %}
			    <option value=0 selected='selected'>----------------</option>
			{% endif %}
			{% if not obj_regelector.sexo == 0 %}
			    <option value=0>----------------</option>
			{% endif %}
			{% if obj_regelector.sexo == 'M' %}
			    <option value='M' selected='selected'>Masculino</option>
			{% endif %}
			{% if obj_regelector.sexo == 'M' %}
			    <option value='M'>Masculino</option>
			{% endif %}
			{% if obj_regelector.sexo == 'F' %}
			    <option value='F' selected='selected'>Femenino</option>
			{% endif %}
			{% if obj_regelector.sexo == 'F' %}
			    <option value='F'>Femenino</option>
			{% endif %}
		    </select>
		</td>
	    </tr>
	    <tr>
		<td>Estado:</td>
		<td>
		    <select required id="id_cod_estado" name="cod_estado" style='width:200px;'/>
			<option value=0>----------------</option>
			{% for e in estados %}
			    {% if e.cod_estado == obj_regelector.cod_estado_id %}
				<option value='{{e.cod_estado}}' selected='selected'>{{e.estado}}</option>
			    {% endif %}
			    {% if not e.cod_estado == obj_regelector.cod_estado_id%}
				<option value='{{e.cod_estado}}'>{{e.estado}}</option>
			    {% endif %}
			{% endfor %}
		    </select>
		</td>
	    </tr>
	    <tr>
		<td>Municipio:</td>
		<td>
		    <select required id="id_cod_municipio" name="cod_municipio" style='width:200px;'>
			<option value=0>----------------</option>
			    {% for m in municipios %}
				{% if m.cod_municipio == obj_regelector.cod_municipio_id %}
				    <option value='{{m.cod_municipio}}' selected='selected'>{{m.municipio}}</option>
				{% endif %}
				{% if not m.cod_municipio == obj_regelector.cod_municipio_id %}
				    <option value='{{m.cod_municipio}}'>{{m.municipio}}</option>
				{% endif %}
			    {% endfor %}
		    </select>
		</td>
	    </tr>
	    <tr>
		<td>Parroquia:</td>
		<td>
		    <select required id="id_cod_parroquia" name="cod_parroquia" style='width:200px;'>
			<option value=0>----------------</option>
			    {% for p in parroquias %}
				{% if p.cod_parroquia == obj_regelector.cod_parroquia_id %}
				    <option value='{{p.cod_parroquia}}' selected='selected'>{{p.parroquia}}</option>
				{% endif %}
				{% if not p.cod_parroquia == obj_regelector.cod_parroquia_id %}
				    <option value='{{p.cod_parroquia}}'>{{p.parroquia}}</option>
				{% endif %}
			    {% endfor %}
		    </select>
		</td>
	    </tr>
	    <tr>
		<td>Centro de votación:</td>
	    </tr>
	    </table>
	    <table>
	    <tr>
		<td>
		    <select required id="id_cod_nuevo" name="cod_nuevo" style='width:390px;'>
			<option value=0>----------------------------------------------------------------</option>
			{% for cv in centros %}
			    {% if cv.cod_n == obj_regelector.cod_nuevo_id %}
				<option value='{{cv.cod_n}}' selected='selected'>{{cv.c_votacion}}</option>
			    {% endif %}
			    {% if not cv.cod_n == obj_regelector.cod_nuevo_id %}
				<option value='{{cv.cod_n}}'>{{cv.c_votacion}}</option>
			    {% endif %}
			{% endfor %}
		    </select>
		    <input type='hidden' id='id_cod_viejo' name='cod_viejo' value='{{obj_regelector.cod_viejo}}'>
		    <input type='hidden' id='id_mun' name='mun' value='{{obj_regelector.mun}}'>
		</td>
	    </tr>
	    <tr>
		<td><input type="submit" value="Actualizar"/></td>
	    </tr>
	</table>
    </form>
</body>
{% endblock contenido %} <!-- Cierre de la carga de datos en el bloque 'contenido' de la plantilla 'base' -->

templates/registroElectoral/elector.html
{% extends "base/base.html" %} <!-- Heredando (Bloque) plantilla index -->

{% block title %}Registrar Electores{% endblock title%} <!--Bloque para definir el título-->



{% block contenido %} <!-- Apertura de la carga de datos en el bloque 'contenido' de la plantilla 'base' -->
<body>
    <h1>Registrar Electores</h1>
    <form method="post">
	{% csrf_token %}
	<!--{{form.as_p}}-->
	<table style="text-align:center;">
	    <tr>
		<td colspan="2" style='background-color: #D9EDF7'>
		    Registrar elector
		</td>
	    </tr>
	    <tr>
		<td>Nacionalidad:</td>
		<td>
		  <select type='text' required id="id_nac" name="nac" style='width:200px;'>
		    <option value='V'>Venezolano</option>
		    <option value='E'>Extranjero</option>
		  </select>
		</td>
	    </tr>
	    <tr>
		<td>Cédula:</td>
		<td><input id="id_cedula" required maxlength="50" name="cedula" type="text" />
		</td>
	    </tr>
	    <tr>
		<td>Primer Apellido:</td>
		<td><input type='text'  id="id_p_apellido" name="p_apellido"/></td>
	    </tr>
	    <tr>
		<td>Segundo Apellido:</td>
		<td><input type='text'  id="id_s_apellido" name="s_apellido"/></td>
	    </tr>
	    <tr>
		<td>Primer Nombre:</td>
		<td><input type='text'  id="id_p_nombre" name="p_nombre"/></td>
	    </tr>
	    <tr>
		<td>Segundo Nombre:</td>
		<td><input type='text'  id="id_s_nombre" name="s_nombre"/></td>
	    </tr>
	    <tr>
		<td>Fecha de Nacimiento:</td>
		<td><input type='text' required id="datepicker" name="f_nac"/></td>
	    </tr>
	    <tr>
		<td>Sexo:</td>
		<td>
		  <select required id="id_sexo" name="sexo" style='width:200px;'>
		    <option value=0>----------------</option>
		    <option value='M'>Masculino</option>
		    <option value='F'>Femenino</option>
		  </select>
		</td>
	    </tr>
	    <tr>
		<td>Estado:</td>
		<td>
		  <select required id="id_cod_estado" name="cod_estado" style='width:200px;'/>
		    <option value=0>----------------</option>
		    {% for e in estados %}
			<option value='{{e.cod_estado}}'>{{e.estado}}</option>
		    {% endfor %}
		  </select>
		</td>
	    </tr>
	    <tr>
		<td>Municipio:</td>
		<td>
		    <select required id="id_cod_municipio" name="cod_municipio" style='width:200px;'>
			<option value=0>----------------</option>
		    </select>
		</td>
	    </tr>
	    <tr>
		<td>Parroquia:</td>
		<td>
		  <select required id="id_cod_parroquia" name="cod_parroquia" style='width:200px;'>
		    <option value=0>----------------</option>
		  </select>
		</td>
	    </tr>
	    <tr>
		<td>Centro de Votación:</td>
	    </tr>
	    </table>
	    <table>
	    <tr>
		<td colspan="2">
		    <select required id="id_cod_nuevo" name="cod_nuevo" style='width:390px;'>
			    <option value=0>------------------------------------------------------------</option>
		    </select>
		    <input type='hidden' id='id_cod_viejo' name='cod_viejo' value='sin codificar'>
		    <input type='hidden' id='id_mun' name='mun' value='sin codificar'>
		</td>
		<td></td>
	    </tr>
	    <tr>
		<td><input type="submit" value="Registrar"/></td>
	    </tr>
	</table>
    </form>
</body>
</html>
{% endblock contenido %} <!-- Cierre de la carga de datos en el bloque 'contenido' de la plantilla 'base' -->

templates/registroElectoral/lista.html
{% extends "base/base.html" %} <!-- Heredando (Bloque) plantilla index -->
    {% block title %}Lista de Electores{% endblock title%}
    {% if form.non_field_errors %}
    <div class="panel">
      {{ form.non_field_errors }}
    </div>
  {% endif %}
  {% block contenido %}
		<script>
		$(document).ready( function () {
		    /*$('#list_registro').DataTable({
			"paging": false,
			language: {
			    search: "Buscar: ",
			}
		    });*/
		    
		    var Tlist_registroE = $('#list_registro').dataTable({
		    "iDisplayLength": 5,
			    "iDisplayStart": 0,
			    "sPaginationType": "full_numbers",
			    "aLengthMenu": [5, 10, 20, 30, 40, 50],
			    "oLanguage": {"sUrl": "/static/js/es.txt"},
			    "aoColumns": [
			    {"sClass": "registro center", "sWidth": "2%"},
			    {"sClass": "registro center", "sWidth": "3%"},
			    {"sClass": "registro center", "sWidth": "4%"},
			    {"sClass": "registro center", "sWidth": "17%"},
			    {"sClass": "registro center", "sWidth": "4%"},
			    {"sClass": "registro center", "sWidth": "8%"},
			    {"sClass": "registro center", "sWidth": "4%"},
			    {"sClass": "registro center", "sWidth": "4%"},
			    {"sWidth": "3%", "bSortable": false, "sClass": "center sorting_false", "bSearchable": false}
			    ]
		    });
		    
		} );
		</script>
    <table style='width: 90em;' id='list_registro'>
			<thead>
      <tr>
        <th colspan=3>
          <a href='/registro_electoral/data'>
            <button hidden=True>Importar Electores</button>
          </a>
        </th>
      </tr>
      <tr>
        <th colspan='9' style='text-align:left;'>
          <a href="/registro_electoral/registrar_elector" title='Nuevo'>  
            Registrar elector
          </a>
        </th>
      </tr>
      <tr style='background-color: #D9EDF7;'>
        <th>Item</th>
        <th>Estado</th>
        <th>Municipio</th>
        <th>Parroquia</th>
        <th>Código</th>
        <th>Centro</th>
				<th>Cédula</td>
				<th>Nombres y Apellidos</th>
				<th colspan=2>Acción</th>
				
      </tr>
      </thead>
			<tbody>
      {% for e in listar_elector %}
      <tr>
        <td>{{e.id}}</td>
        <td>{{ e.cod_estado.estado }}</td>
        <td>
          {% for m in municipio %}
            {% if m.cod_municipio == e.cod_municipio_id %}
              {{m.municipio}}
            {% endif %}
          {% endfor %}
        </td>
        <td>

          {% for p in parroquia %}
            {% if  p.estado_id == e.cod_estado_id and p.municipio == e.cod_municipio_id and p.cod_parroquia == e.cod_parroquia_id%}
              {{p.parroquia}}
            {% endif %}
          {% endfor %}

        </td>
        <td style='color:#145876;'>{{e.cod_nuevo.cod_n}}</td>
        <td>{{e.cod_nuevo.c_votacion}}</td>
        <td>{{e.nac}}-{{ e.cedula }}</td>
        <td>
					
					{% if e.p_apellido %}
						{{ e.p_apellido }}
					{% endif %}
					
					{% if e.s_apellido %}
						{{ e.s_apellido }}
					{% endif %}
					
					{% if e.p_nombre %}
						{{ e.p_nombre }}
					{% endif %}
					
					{% if e.s_nombre %}
						{{ e.s_nombre }}
					{% endif %}
					
					
					</td>
        <td>
          <a href='{% url "actualizar_elector" e.id %}'>
            <img src='../../static/admin/img/icon_changelink.gif' title='Editar'>
          </a>
	  <a onclick="eliminar_data('{{e.id}}', '/registro_electoral/eliminar_elector/')"><!--Forma anterior: href='{% url "eliminar_elector" e.id %}'-->
            <img src='../../static/admin/img/icon_deletelink.gif' title='Eliminar'>
          </a>
        </td>
      </tr>
      {% endfor %}
      </tbody>
    </table>
    {% endblock contenido%}
<!-- ************************************************************* -->