apps/topologia/estados/urls.py
from django.conf.urls import url
from .views import RegistrarEstado ,ActualizarEstado, EliminarEstado,ListarEstado, base_view, load_data

urlpatterns = [
    url(r'^registrar_estado/$','apps.topologia.estados.views.RegistrarEstado'),
    url(r'^actualizar_estado/(?P<pk>\d+)/$','apps.topologia.estados.views.ActualizarEstado', name='actualizar_estado'),
    url(r'^eliminar_estado/(?P<pk>\d+)/$', 'apps.topologia.estados.views.EliminarEstado'),
    #url(r'^registrar_estado/', RegistrarEstado.as_view(), name="registrar_estados",),
    #url(r'^actualizar_estado/(?P<pk>\d+)/$', ActualizarEstado.as_view(), name='actualizar_estado',),
    #url(r'^eliminar_estado/(?P<pk>\d+)/$', EliminarEstado.as_view(), name='eliminar_estado',),
    url(r'^$', 'apps.topologia.estados.views.base_view', name="home",), # URL de Exportacion para la data
    url(r'^lista_estado/$','apps.topologia.estados.views.ListarEstado',name='listar_estados',),
    url(r'^data/', 'apps.topologia.estados.views.load_data', name="datos_estados",), # URL de Exportacion para la data
]

apps/topologia/municipios/urls.py
from django.conf.urls import url
from .views import RegistrarMunicipio, ActualizarMunicipio, EliminarMunicipio,ListarMunicipio, load_data # Importamos las Vistas


urlpatterns = [
    url(r'^registrar_municipio/', 'apps.topologia.municipios.views.RegistrarMunicipio', name="registrar_municipio",),
    url(r'^actualizar_municipio/(?P<pk>\d+)/$', 'apps.topologia.municipios.views.ActualizarMunicipio', name='actualizar_municipio',),
    url(r'^eliminar_municipio/(?P<pk>\d+)/$', 'apps.topologia.municipios.views.EliminarMunicipio', name='eliminar_municipio',),
    url(r'^listar_municipios/$','apps.topologia.municipios.views.ListarMunicipio', name='listar_municipio',),
    url(r'^data/', 'apps.topologia.municipios.views.load_data', name="datos_municipio",), # URL de Exportacion para la data
]

apps/topologia/urls.py
from django.conf.urls import patterns, include, url
from rest_framework.routers import DefaultRouter
from apps.topologia.estados.viewsets import EstadoViewSet
from apps.topologia.municipios.viewsets import MunicipioViewSet
from apps.topologia.parroquias.viewsets import ParroquiaViewset
from apps.centro_votacion.viewsets import CentroVotacionViewSet
from apps.registro.viewsets import RegistroViewSet


router = DefaultRouter()
router.register(r'estados', EstadoViewSet)
router.register(r'municipios', MunicipioViewSet)
router.register(r'parroquias', ParroquiaViewset)
router.register(r'centro_votacion', CentroVotacionViewSet)
router.register(r'registro_electoral', RegistroViewSet)
urlpatterns = patterns('',
                       url(r'^', include(router.urls))
                       )

sistema_consulta/urls.py
from django.conf.urls import include, url
from django.contrib import admin

#urlpatterns = patterns('',
#
#   url(r'^admin/', include(admin.site.urls)),
#
#   url(r'^topologia/',
#   include('apps.topologia.urls')
#                           ),
#                       # PARA AGREGAR LA AUTENTICACION DEL USUARIO
## url(r'^api-auth/',
       # include('rest_framework.urls', namespace='rest_framework')),
#                       url(r'^chaining/',
#                           include('pixelfields_smart_selects.urls')
#                           ),
#
#                       #url(r'^estado/',
#                       #    include('apps.topologia.estados.urls')
#                       #    ),
#
#                       )

urlpatterns = [
    url(r'^administrador/', include(admin.site.urls)),
    url(r'^api/', include('apps.topologia.urls')),
    url(r'^api/', include('apps.centro_votacion.urls')),
    url(r'^', include('apps.registro.urls')),
    # PARA AGREGAR LA AUTENTICACION DEL USUARIO
    #url(r'^api-auth/',
    #    include('rest_framework.urls', namespace='rest_framework')),
    url(r'^chaining/', include('pixelfields_smart_selects.urls')),

    url(r'^estado/', include('apps.topologia.estados.urls')),
    url(r'^', include('apps.topologia.estados.urls')),
    url(r'^municipio/', include('apps.topologia.municipios.urls')),
    url(r'^parroquia/', include('apps.topologia.parroquias.urls')),
    url(r'^centro_votacion/', include('apps.centro_votacion.urls')), # Url para centro de votacion
    url(r'^registro_electoral/', include('apps.registro.urls')), # Url para centro de votacion
    url(r'^iniciar/', include('apps.login.urls')),
]

apps/topologia/estados/models.py
from django.db import models

# Esta es mi CLASE.


class Estado(models.Model):
    """Esta es la Clase que define todo lo referente a los estados
        Registrar Modificar Eliminar y Consultar
    """
    cod_estado  = models.IntegerField(unique=True)
    estado      = models.CharField(max_length=50)
    user        = models.CharField(max_length=15, null=True, blank=True)
    date_create = models.DateTimeField(auto_now_add=True, auto_now=False, null=True)
    date_update = models.DateTimeField(auto_now_add=False, auto_now=True, null=True)
    
    

    def __unicode__(self):
        return self.estado

apps/topologia/municipios/models.py
from django.db import models
from ..estados.models import Estado


class Municipio(models.Model):
    municipio     = models.CharField(verbose_name="Municipio", max_length=50)
    cod_municipio = models.IntegerField(null=True)
    estado        = models.ForeignKey(Estado, to_field='cod_estado', on_delete=models.SET_NULL, related_name='estado_municipio', null=True) # Clave unica que hace referencia a estado a traves de cod_estado con clave unica (unique)
    user          = models.CharField(max_length=15, null=True)
    date_create   = models.DateTimeField(auto_now_add=True, auto_now=False, null=True)
    date_update   = models.DateTimeField(auto_now_add=False, auto_now=True, null=True)

    def __unicode__(self):
        return self.municipio

apps/topologia/parroquias/models.py
from django.db import models
from smart_selects.db_fields import ChainedForeignKey
from ..estados.models import Estado
from ..municipios.models import Municipio


class Parroquia(models.Model):
	"""Esta es la Clase que define todo lo referente a los parroquias
		Registrar Modificar Eliminar y Consultar
	"""
	parroquia     = models.CharField(max_length=50)
	estado        = models.ForeignKey(Estado, to_field='cod_estado', on_delete=models.SET_NULL, related_name='estado_parroquia', null=True)
	cod_parroquia = models.IntegerField(null=True)
	municipio     = models.IntegerField(null=True)
	user          = models.CharField(max_length=15, null=True)
	date_create   = models.DateTimeField(auto_now_add=True, auto_now=False, null=True)
	date_update   = models.DateTimeField(auto_now_add=False, auto_now=True, null=True)

	def __unicode__(self):
		return self.parroquia

	def __str__(self):
		return self.parroquia

apps/topologia/estados/forms.py
from django.forms import ModelForm
from django import forms
from apps.topologia.estados.models import Estado

class FormEstado(ModelForm):
    class Meta:
	model = Estado
	exclude = {'user',}

apps/topologia/municipios/forms.py
from django.forms import ModelForm
from django import forms
from apps.topologia.municipios.models import Municipio

class FormMunicipio(ModelForm):
    class Meta:
	model = Municipio
	exclude = {'user',}

apps/topologia/parroquias/forms.py
from django.forms import ModelForm
from django import forms
from apps.topologia.parroquias.models import Parroquia

class FormParroquia(ModelForm):
    class Meta:
        model = Parroquia
        exclude = {'user',}

apps/topologia/estados/views.py
#encoding:utf-8
from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from .models import Estado
from .forms import FormEstado
from django.views.generic.dates import ArchiveIndexView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render_to_response
from django.contrib import messages # Metodo para la validacion de los campos
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger # Paginacion
from django.contrib.auth.decorators import login_required # Forma para impedir el acceso al sistema
import os
import csv
#=====================================================================================
#                            # Clase RegistrarEstado
#=====================================================================================
@login_required(login_url='/iniciar/login/')
def RegistrarEstado(request):
    if request.method=='POST':
        form_regestado = FormEstado(request.POST, request.FILES)
        if form_regestado.is_valid():
            nuevo_regestado = form_regestado.save(commit=False)
            nuevo_regestado.user = request.user.username
            nuevo_regestado.save()
	    return HttpResponseRedirect('/estado/lista_estado')
    else:
         form_regestado = FormEstado()
    ctx = {'form_regestado':form_regestado} # ctx = Contexto
    return render_to_response('topologia/estado/registrar_estado.html',ctx, context_instance=RequestContext(request))
    

#=====================================================================================
                            # Clase ActualizarEstado
#=====================================================================================
@login_required(login_url='/iniciar/login/')
def ActualizarEstado(request,pk):
    obj_regestado = Estado.objects.get(id=pk)
    if request.method=='POST':
        form_regestado = FormEstado(request.POST, request.FILES, instance=obj_regestado)
        if form_regestado.is_valid():
            edit_regestado = form_regestado.save(commit=False)
            edit_regestado.user = request.user.username
            edit_regestado.save()
            return HttpResponseRedirect('/estado/lista_estado')
    else:
        form_regestado = FormEstado(instance=obj_regestado)
    ctx = {'form_regestado':form_regestado,'obj_regestado':obj_regestado} # ctx = Contexto
    return render_to_response('topologia/estado/actualizar_estado.html',ctx, context_instance=RequestContext(request))

#=====================================================================================
                            # Clase EliminarEstado
#=====================================================================================
def EliminarEstado(request,pk):
    obj_regestado = Estado.objects.get(id=pk)
    obj_regestado.delete()
    return HttpResponseRedirect('/estado/lista_estado')
#======================================================================================
# Metodo para listar Registros y Paginacion
#======================================================================================
@login_required(login_url='/iniciar/login/')
def ListarEstado(request):
    estado    = Estado.objects.all()
    paginator = Paginator(estado, 5) # Show 5 contacts per page
    page      = request.GET.get('page')
    try:
        lista_estados    = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        lista_estados = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        lista_estados = paginator.page(paginator.num_pages)
    ctx          = {'lista_estados':lista_estados,} # ctx = Contexto
    return render_to_response('topologia/estado/lista_estado.html',ctx, context_instance=RequestContext(request))

#======================================================================================
                    # Metodo para renderizar a /
#=====================================================================================

def base_view(request):
    
    return render_to_response('base/base.html',locals(), context_instance=RequestContext(request))
#======================================================================================
# Url Importar data CSV
#======================================================================================
@login_required(login_url='/iniciar/login/')
def load_data(request):

    os.path.dirname(os.path.abspath(__file__))

    DIR_URL = os.getcwd()

    reader = csv.reader(open(DIR_URL+str("/apps/topologia/estados/script/estados.csv")))
    
    # Recorrido de los registros
    for row in reader:
        data = row[0].split(';')
        centro = Estado(
            cod_estado     = data[0],
            estado         = data[1],
            )
        centro.save()
    return HttpResponseRedirect('/estado/lista_estado')
#======================================================================================

def custom_404(request):
    return render_to_response('404.html', RequestContext(request))

apps/topologia/municipios/views.py
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from .models import Municipio # Modelo Municipio
from .forms import FormMunicipio # Vista Forms Municipio
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger # Paginacion
from django.contrib.auth.decorators import login_required # Forma para impedir el acceso al sistema
import csv # Libreria para inportar CSV
import os
from apps.topologia.estados.models import Estado

#=====================================================================================
#                            # Metodo RegistrarMunicipio
#=====================================================================================
@login_required(login_url='/iniciar/login/')
def RegistrarMunicipio(request):
    lista_estado = Estado.objects.all()
    mun          = Municipio.objects.all()
    count_m      = len(mun) + 1
    if request.method=='POST':
        form_reg_mun = FormMunicipio(request.POST, request.FILES)
        if form_reg_mun.is_valid():
            new_reg_mun = form_reg_mun.save(commit=False)
            new_reg_mun.user = request.user.username
            new_reg_mun.save()
	    return HttpResponseRedirect('/municipio/listar_municipios')
    else:
        form_reg_mun = FormMunicipio()
    ctx = {'form_reg_mun':form_reg_mun,'lista_estado':lista_estado,'count_m':count_m }
    return render_to_response('topologia/municipio/registrar_municipio.html',ctx, context_instance=RequestContext(request))

#=====================================================================================
#                            # Clase RegistrarEstado
#=====================================================================================

@login_required(login_url='/iniciar/login/')
def ActualizarMunicipio(request,pk):
    lista_estado = Estado.objects.all()
    obj_reg_mun = Municipio.objects.get(id=pk)
    if request.method=='POST':
        form_reg_mun = FormMunicipio(request.POST, request.FILES, instance=obj_reg_mun)
        if form_reg_mun.is_valid():
            edit_reg_mun = form_reg_mun.save(commit=False)
            edit_reg_mun.user = request.user.username
            edit_reg_mun.save()
            return HttpResponseRedirect('/municipio/listar_municipios')
    else:
        form_reg_mun = FormMunicipio(instance=obj_reg_mun)
    ctx = {'form_reg_mun':form_reg_mun,'obj_reg_mun':obj_reg_mun,'lista_estado':lista_estado} # ctx = Contexto
    return render_to_response('topologia/municipio/actualizar_municipio.html',ctx, context_instance=RequestContext(request))

#=====================================================================================
#                            # Clase RegistrarEstado
#=====================================================================================
@login_required(login_url='/iniciar/login/')
def EliminarMunicipio(request,pk):
    obj_mun = Municipio.objects.get(id=pk)
    obj_mun.delete()
    return HttpResponseRedirect('/municipio/listar_municipios')

#======================================================================================
              # Metodo para listar Registros y Paginacion
#======================================================================================
@login_required(login_url='/iniciar/login/')
def ListarMunicipio(request):
    municipio    = Municipio.objects.all()
    paginator    = Paginator(municipio, 5) # Show 5 contacts per page
    page         = request.GET.get('page')
    try:
        lista_municipio    = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        lista_municipio    = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        lista_municipio    = paginator.page(paginator.num_pages)
    ctx          = {'lista_municipio':lista_municipio,} # ctx = Contexto
    return render_to_response('topologia/municipio/lista_municipio.html',ctx, context_instance=RequestContext(request))

#======================================================================================
# Url Importar data CSV
#======================================================================================
@login_required(login_url='/iniciar/login/')
def load_data(request):

    os.path.dirname(os.path.abspath(__file__))

    DIR_URL = os.getcwd()

    reader = csv.reader(open(DIR_URL+str("/apps/topologia/municipios/script/municipio.csv")))
    
    # Recorrido de los registros
    for row in reader:
        data = row[0].split(';')
        centro = Municipio(
            municipio      = data[0],
            cod_municipio  = data[2],
            estado_id      = data[1],
            )
        centro.save()
    return HttpResponseRedirect('/municipio/listar_municipios')
#======================================================================================

templates/topologia/parroquia/actualizar_parroquias.html
{% extends "base/base.html" %} <!-- Bloque, Plantilla base -->
    {% block title %}Actualizar Parroquias{% endblock %}
    
    {% block contenido %}
	<form method="post">
	    {% csrf_token %}
	    <table border='0'>
	    	<tr>
	    	    <td colspan='2' style='background-color: #D9EDF7'>Actualizar Parrroquia</td>
	    	</tr>
	    	<tr>
		    <td>Código</td>
		    <td><input id="id_cod_parroquia" required=True name="cod_parroquia" type="number" value='{{obj_reg_parr.cod_parroquia}}' required=True/></td>
	    	</tr>
	    	<tr>
		    <td>Estado</td>
		    <td>
			<select id="id_cod_estado" name="estado" required=True>
			    <option value="">-----------------------------</option>
			    {% for e in list_e %}
				{% if e.cod_estado == obj_reg_parr.estado_id%}
				    <option value='{{e.cod_estado}}' selected='selected'>{{ e.estado }}</option>
				{% endif %}
				{% if not e.cod_estado == obj_reg_parr.estado_id %}
				    <option value='{{e.cod_estado}}'>{{ e.estado }}</option>
				{% endif %}
			    {% endfor %}
			</select>
		    </td>
	    	</tr>
	    	<tr>
		    <td>Municipio</td>
		    <td>
			<select id="id_cod_municipio" name="municipio" required=True>
			    <option value="">-----------------------------</option>
			    {% for est in list_e%}
				    {% for m in list_m %}
						{% if est.cod_estado == obj_reg_parr.estado_id and m.cod_municipio == obj_reg_parr.municipio%}
						<option value='{{m.cod_municipio}}' selected='selected'>{{m.municipio}}</option>
					    {% endif %}
					    {% if not m.cod_municipio == obj_reg_parr.municipio %}
						<option value='{{m.cod_municipio}}'>{{m.municipio}}</option>
					    {% endif %}
				    {% endfor %}
			    {%endfor%}
			</select>
		    </td>
		    </tr>
		    <tr>
			<td>Parroquia</td>
			<td><input id="id_parroquia" maxlength="50" name="parroquia" type="text" value='{{obj_reg_parr.parroquia}}' required=True/></td>
		    </tr>
	    	<tr>
	    	    <td colspan='2'>
			<input type="submit" value="Actualizar"/>
		    </td>	
	    	</tr>
	    </table>
	</form>
    {% endblock contenido%}

templates/topologia/parroquia/eliminar_parroquias.html
{% extends "base/base.html" %} <!-- Bloque, Plantilla base -->
    {% block title %}Eliminar Parroquia{% endblock %}
    
    {% block contenido %}
	<form method="post">{% csrf_token %}
		¿ Esta seguro que desea eliminar el registro "{{ object }}"?
		<input type="submit" value="Eliminar" />
	</form>
	{% endblock contenido%}

templates/topologia/parroquia/lista_parroquia.html
{% extends "base/base.html" %} <!-- Heredando (Bloque) plantilla index -->
	{% block title %}Lista de Parroquias{% endblock title%}
	{% if form.non_field_errors %}
	<div class="panel">
	  {{ form.non_field_errors }}
	</div>
	{% endif %}

	{% block contenido %}
	<!-- ************************************************************* -->
	    <table style='width:800px;'>
	      <tr>
		<td colspan=3>
		  <a href='/parroquia/data'>
		  	{% if user.username == "admin" %}
		    	<button>Importar Parroquias</button>
		    {% endif %}
		  </a>
		</td>
	      </tr>
	      <tr>
	      <td style='text-align: left' colspan='6'>
		  <a href="/parroquia/registrar_parroquia" title='Nuevo'>  
		    Registrar Parroquia
		  </a>
		</td>
	      </tr>
	      <tr style='background-color: #D9EDF7;text-align: center;'>
	    <td width="10px;">Item</td>
		<td width="150px;">Estado</td>
		<td>Municipio</td>
		<td>Parroquia</td>
		<td colspan=3>Acción</td>
	      </tr>
	      {% for p in list_parroquia %}
	      <tr style='text-align: center;' class="{% cycle 'impar' 'par' %}">
	    <td>{{p.id}}</td>
		<td>{{ p.estado }}</td>
		<td>
			{% for m in municipio %}
				{% if m.cod_municipio == p.municipio %}
					{{m.municipio}}
				{% endif %}
			{% endfor %}

		</td>
		<td>{{ p.parroquia }}</td>
		<td>
		  <a href='{% url "actualizar_parroquia" p.id %}'>
		    <img src='../../static/admin/img/icon_changelink.gif' title='Editar'>
		  </a>
		</td>
		<td>
		  <a onclick="eliminar_data('{{p.id}}','/parroquia/eliminar_parroquia/')">
		    <img src='../../static/admin/img/icon_deletelink.gif' title='Eliminar'></td>
		  </a>
	      </tr>
	      {% empty %}
	      <tr style='text-align: center;'>
		<td colspan=2>No se encuentran registros</td>
	      </tr>
	      {% endfor %}
	    </table>
	    <div class="pagination" style='margin-left: 15em;'>
	    <span class="step-links">
	      {% if list_parroquia.has_previous %}
		<a href="?page={{ list_parroquia.previous_page_number }}">Anterior</a>
	      {% endif %}
	    <span class="current">
	      Página {{ list_parroquia.number }} de {{ list_parroquia.paginator.num_pages }}.
	    </span>
	    {% if list_parroquia.has_next %}
	      <a href="?page={{ list_parroquia.next_page_number }}">Siguiente</a>
	    {% endif %}
	    </span>
	    </div>
	{% endblock contenido%}
	<!-- ************************************************************* -->

templates/topologia/parroquia/parroquias.html
{% extends "base/base.html" %} <!-- Bloque, Plantilla base -->
    {% block title %}Registrar Parroquias{% endblock %}
    
    {% block extra_head %}
	<script src="{{STATIC_URL}}js/jquery-1.11.2.min.js"></script>
    {% endblock extra_head %}
    
    <script src="{{STATIC_URL}}js/jquery-1.11.2.min.js"></script>
    {% block contenido %}
	<form method="post">
	    {% csrf_token %}
	    {{form.as_p}}
	<input type="submit" value="Registrar"/>
	</form>
	<a href='/parroquia/data'>
	    <button>Exportar Parroquias</button>
	</a>
    {% endblock contenido%}

templates/topologia/parroquia/registrar_parroquias.html
{% extends "base/base.html" %} <!-- Bloque, Plantilla base -->
    {% block title %}Registrar Parroquias{% endblock %}
    
    {% block contenido %}
	<form method="post">
	    {% csrf_token %}
	    <table border='0'>
	    	<tr>
	    	    <td colspan='2' style='background-color: #D9EDF7'>Registrar Parrroquia</td>
	    	</tr>
	    	<tr>
		    <td>Código</td>
		    <td><input id="id_cod_parroquia" required=True name="cod_parroquia" type="number" required=True /></td>
	    	</tr>
	    	<tr>
		    <td>Estado</td>
		    <td>
			<select id="id_cod_estado" name="estado" required=True>
			    <option value="">-----------------------------</option>
			    {% for e in list_e %}
			    <option value='{{e.cod_estado}}'>{{ e.estado }}</option>
			    {% endfor %}
			</select>
		    </td>
	    	</tr>
	    	<tr>
		    <td>Municipio</td>
		    <td>
			<select id="id_cod_municipio" name="municipio" required=True>
			    <option value="">-----------------------------</option>
			</select>
		    </td>
		    </tr>
		    <tr>
			<td>Parroquia</td>
			<td><input id="id_parroquia" maxlength="50" name="parroquia" type="text" required=True/></td>
		    </tr>
	    	<tr>
	    	    <td colspan='2'>
			<input type="submit" value="Registrar"/>
		    </td>	
	    	</tr>
	    </table>
	</form>
    {% endblock contenido%}