apps/centro_votacion/urls.py
from django.conf.urls import patterns, url
from apps.centro_votacion.views import RegistrarCentroVotacion, ActualizarCentroVotacion, EliminarCentroVotacion, ListarCentroVotacion, BuscarAjax, load_data # Importamos las Vistas de centro de votacion

# URL para Centro de Votacion
urlpatterns = [
    url(r'^registrar_centro/', 'apps.centro_votacion.views.RegistrarCentroVotacion', name="registrar_centro",),
    url(r'^actualizar_centro/(?P<pk>\d+)/$', 'apps.centro_votacion.views.ActualizarCentroVotacion', name='actualizar_centro',),
    url(r'^eliminar_centro/(?P<pk>\d+)/$', 'apps.centro_votacion.views.EliminarCentroVotacion', name='eliminar_centro',),
    url(r'^listar_centro_votacion/$','apps.centro_votacion.views.ListarCentroVotacion', name='listar_centro_votacion',),
    url(r'^busquedaajax/$','apps.centro_votacion.views.BuscarAjax'),
    url(r'^data/', 'apps.centro_votacion.views.load_data', name="datos_municipio",), # URL de Exportacion para la data
]

sistema_consulta/urls.py
from django.conf.urls import include, url
from django.contrib import admin

#urlpatterns = patterns('',
#
#   url(r'^admin/', include(admin.site.urls)),
#
#   url(r'^topologia/',
#   include('apps.topologia.urls')
#                           ),
#                       # PARA AGREGAR LA AUTENTICACION DEL USUARIO
## url(r'^api-auth/',
       # include('rest_framework.urls', namespace='rest_framework')),
#                       url(r'^chaining/',
#                           include('pixelfields_smart_selects.urls')
#                           ),
#
#                       #url(r'^estado/',
#                       #    include('apps.topologia.estados.urls')
#                       #    ),
#
#                       )

urlpatterns = [
    url(r'^administrador/', include(admin.site.urls)),
    url(r'^api/', include('apps.topologia.urls')),
    url(r'^api/', include('apps.centro_votacion.urls')),
    url(r'^', include('apps.registro.urls')),
    # PARA AGREGAR LA AUTENTICACION DEL USUARIO
    #url(r'^api-auth/',
    #    include('rest_framework.urls', namespace='rest_framework')),
    url(r'^chaining/', include('pixelfields_smart_selects.urls')),

    url(r'^estado/', include('apps.topologia.estados.urls')),
    url(r'^', include('apps.topologia.estados.urls')),
    url(r'^municipio/', include('apps.topologia.municipios.urls')),
    url(r'^parroquia/', include('apps.topologia.parroquias.urls')),
    url(r'^centro_votacion/', include('apps.centro_votacion.urls')), # Url para centro de votacion
    url(r'^registro_electoral/', include('apps.registro.urls')), # Url para centro de votacion
    url(r'^iniciar/', include('apps.login.urls')),
]

apps/centro_votacion/models.py
# -*- coding: utf-8 -*-
from django.db import models
from smart_selects.db_fields import ChainedForeignKey
from apps.topologia.estados.models import Estado
from apps.topologia.municipios.models import Municipio # Importamos el Modelo Municipio
from apps.topologia.parroquias.models import Parroquia # Importamos el Modelo Parroquia

# Modelo de Topologia / Centro de Votacion

# Clase de estado
class CentroVotacion(models.Model):
    """Esta es la Clase que define todo lo referente a los Centros de Votacion
        Registrar Modificar Eliminar y Consultar
    """
    estado      = models.ForeignKey(Estado, to_field='cod_estado', on_delete=models.SET_NULL, related_name='estado_centro_votacion', null=True)
    municipio   = models.IntegerField(null=True)
    parroquia   = models.IntegerField(null=True)
    id_mun      = models.IntegerField(null=True)
    cod_n       = models.IntegerField(verbose_name="Cod Nuevo", max_length=11, unique=True, null= True)
    cod_v       = models.CharField(verbose_name="Cod Viejo", max_length=11, unique=False, null= True)
    c_votacion  = models.TextField(max_length=1500, verbose_name='Centro de Votacion')
    direccion   = models.TextField(max_length=1500, verbose_name='Direccion')
    user        = models.CharField(max_length=15, null=True)
    date_create = models.DateTimeField(auto_now_add=True, auto_now=False, null=True)
    date_update = models.DateTimeField(auto_now_add=False, auto_now=True, null=True)
    

    def __unicode__(self):
        return self.c_votacion

    def __str(self):
        return self.c_votacion

apps/registro/models.py
# -*- encoding: utf-8 -*-
from django.db import models
#from smart_selects.db_fields import ChainedForeignKey
from smart_selects.db_fields import ChainedForeignKey
from django.core.urlresolvers import reverse
from apps.topologia.estados.models import Estado
from apps.topologia.municipios.models import Municipio
from apps.topologia.parroquias.models import Parroquia
from apps.centro_votacion.models import CentroVotacion
import datetime
from django.contrib.humanize.templatetags.humanize import naturalday, naturaltime

# Create your models here.
NACIONALIDAD = (
    ('V', 'Venezolano'),
    ('E', 'Extranjero'),
)

SEXO = (
    ('M', 'Masculino'),
    ('F', 'Femenino'),
)

class RegistroElectoral(models.Model):
    
    nac = models.CharField(verbose_name="Nacionalidad", max_length=1, choices=NACIONALIDAD, default='V')
    cedula = models.CharField(verbose_name="Cédula", max_length=8, unique=True, null=True)
    p_apellido = models.CharField(verbose_name="Primer Apellido", max_length=200, null=True)
    s_apellido = models.CharField(verbose_name="Segundo Apellido", max_length=200, null=True)
    p_nombre = models.CharField(verbose_name="Primer Nombre", max_length=200, null=True)
    s_nombre = models.CharField(verbose_name="Segundo Nombre", max_length=200, null=True)
    f_nac = models.DateField('Fecha de nacimiento', null=True)
    sexo = models.CharField(verbose_name="Sexo", max_length=1, choices=SEXO, null=True)
    cod_estado = models.ForeignKey(Estado, to_field='cod_estado', on_delete=models.SET_NULL, related_name='estado_registro', null=True)
    cod_municipio = models.ForeignKey(Municipio)
    cod_parroquia = models.ForeignKey(Parroquia)
    cod_nuevo = models.ForeignKey(CentroVotacion, to_field='cod_n', on_delete=models.SET_NULL, related_name='centro_registro', null=True)
    cod_viejo = models.CharField(verbose_name="Código anterior", max_length=20, null=True)
    date_create = models.DateTimeField(auto_now_add=True, auto_now=False, null=True)
    date_update = models.DateTimeField(auto_now_add=False, auto_now=True, null=True)
    user = models.CharField(max_length=15, null=True)
    mun = models.CharField(max_length=30, null=True)



    def __unicode__(self):
        # Método para retornar por defecto el valor de un campo especificado
        return self.cedula

apps/centro_votacion/forms.py
from django.forms import ModelForm
from django import forms
from apps.centro_votacion.models import CentroVotacion

class CentroVotacionForm(ModelForm):
    class Meta:
        model   = CentroVotacion
        exclude = {'user',} 

apps/centro_votacion/views.py
# -*- coding: utf-8 -*-
from django.views.generic import CreateView, UpdateView, DeleteView
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.core.urlresolvers import reverse_lazy
from apps.topologia.estados.models import Estado # Modelo Estado
from apps.topologia.municipios.models import Municipio # Modelo Municipio
from apps.topologia.parroquias.models import Parroquia # modelo Parroquia
from .models import CentroVotacion  # Importamos el modelo centro_votacion
from .forms import CentroVotacionForm # Clase Form Centro votacion
from django.http import HttpResponse, HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger # Paginacion
from django.contrib.auth.decorators import login_required # Forma para impedir el acceso al sistema
from django.core import serializers
import csv
import os
from django.db import connection

#======================================================================================
                           # Metodo RegistrarCentroVotacion
#======================================================================================
@login_required(login_url='/iniciar/login/')
def RegistrarCentroVotacion(request):
    list_estado  = Estado.objects.all() # Modelo de consulta a Estado
    if request.method=='POST':
        form_reg_centro_votacion = CentroVotacionForm(request.POST, request.FILES)
        if form_reg_centro_votacion.is_valid():
            new_reg_centro_votacion = form_reg_centro_votacion.save(commit=False)
            new_reg_centro_votacion.user = request.user.username
            new_reg_centro_votacion.save()
	    return HttpResponseRedirect('/centro_votacion/listar_centro_votacion')
    else:
        form_reg_centro_votacion = CentroVotacionForm()
    ctx = {'form_reg_centro_votacion':form_reg_centro_votacion,'list_estado':list_estado} # ctx = Contexto
    return render_to_response('centro_votacion/registrar_centro_votacion.html',ctx, context_instance=RequestContext(request))

#=====================================================================================
                            # Clase ActualizarCentroVotacion
#=====================================================================================
@login_required(login_url='/iniciar/login/')
def ActualizarCentroVotacion(request,pk):
    obj_reg_cen = CentroVotacion.objects.get(id=pk)
    
    list_estado  = Estado.objects.all()
    #list_mun     = Municipio.objects.all()
    #list_par     = Parroquia.objects.all()
    list_mun     = Municipio.objects.filter(estado_id=obj_reg_cen.estado_id)
    list_par     = Parroquia.objects.filter(estado_id=obj_reg_cen.estado_id,municipio=obj_reg_cen.municipio)

    if request.method=='POST':
        obj_reg_edit_cen = CentroVotacionForm(request.POST, request.FILES, instance=obj_reg_cen)
        if obj_reg_edit_cen.is_valid():
            new_reg_cen = obj_reg_edit_cen.save(commit=False)
            new_reg_cen.user = request.user.username
            new_reg_cen.save()
            return HttpResponseRedirect('/centro_votacion/listar_centro_votacion')
    else:
        obj_reg_edit_cen = CentroVotacionForm(instance=obj_reg_cen)
    ctx = {'obj_reg_edit_cen':obj_reg_edit_cen,'obj_reg_cen':obj_reg_cen,'list_estado':list_estado,'list_mun':list_mun,'list_par':list_par,} # ctx = Contexto
    return render_to_response('centro_votacion/actualizar_centro_votacion.html',ctx, context_instance=RequestContext(request))

#=====================================================================================
                            # Metodo EliminarEstado
#=====================================================================================
@login_required(login_url='/iniciar/login/')
def EliminarCentroVotacion(request,pk):
    obj_reg_cen = CentroVotacion.objects.get(id=pk)
    obj_reg_cen.delete()
    return HttpResponseRedirect('/centro_votacion/listar_centro_votacion')

#======================================================================================
# Metodo para listar Registros y Paginacion
#======================================================================================
@login_required(login_url='/iniciar/login/')
def ListarCentroVotacion(request):
    c_votacion = CentroVotacion.objects.all().order_by('id','estado_id','id_mun','parroquia')
    municipio = Municipio.objects.all()
    parroquia = Parroquia.objects.all()
   
    paginator  = Paginator(c_votacion, 20) # Show 5 contacts per page
    page       = request.GET.get('page')
    try:
        list_centro_votacion = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        list_centro_votacion = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        list_centro_votacion = paginator.page(paginator.num_pages)

    array = {
        'list_centro_votacion' : list_centro_votacion,
        'municipio' : municipio,
        'parroquia' : parroquia,
    }
    return render_to_response('centro_votacion/lista_centro_votacion.html', array, context_instance = RequestContext(request))


#======================================================================================
#                         Metodo para la busqueda del pk municipio
#======================================================================================
def BuscarAjax(request):
	id_est     = request.GET['id_est']
	id_mun     = request.GET['id_mun']
	municipios = Municipio.objects.filter(estado_id=id_est,cod_municipio=id_mun)
	for x in municipios:
		id = x.id
		return HttpResponse(id, content_type='application/json')

#======================================================================================
#                                 Url Importar data CSV
#======================================================================================
@login_required(login_url='/iniciar/login/')
def load_data(request):
    
    os.path.dirname(os.path.abspath(__file__))

    DIR_URL = os.getcwd()
    
    reader = csv.reader(open(DIR_URL+str("/apps/centro_votacion/script/centros_votacion.csv")))
    
    for row in reader:
        data = row[0].split(';')
        obj_m = Municipio.objects.filter(estado_id=data[0],cod_municipio=data[1])
        for x in obj_m:
        	id_mun = x.id
        centro = CentroVotacion(
            c_votacion      = data[5],
            direccion       = data[6],
            estado_id       = data[0],
            municipio       = data[1],
            parroquia       = data[2],
            id_mun          = id_mun,
            cod_n           = data[3],
            cod_v           = data[4]
            )
        centro.save()
        
    return HttpResponseRedirect('/centro_votacion/listar_centro_votacion')
#======================================================================================

templates/centro_votacion/actualizar_centro_votacion.html
{% extends "base/base.html" %} <!-- Bloque, Plantilla base -->
    {% block title %}Actualizar Centro de Votación{% endblock %}
    
    {% block contenido %}
	<form method="post">
	    {% csrf_token %}
	    <table>
		<tr>
		    <td colspan='6' style='background-color: #D9EDF7'>Actualizar Centro Votación</td>
		</tr>
		<tr>
		    <td>Estado</td>
		    <td>
			<select id="id_cod_estado" name="estado" required=True style='width: 200px;'>
			    <option value="">-----------------------------</option>

			    {% for e in list_estado %}
				{% if e.cod_estado == obj_reg_cen.estado_id%}
				    <option value='{{e.cod_estado}}' selected='selected'>{{ e.estado }}</option>
				{% endif %}
				{% if not e.cod_estado == obj_reg_cen.estado_id %}
				    <option value='{{e.cod_estado}}'>{{ e.estado }}</option>
				{% endif %}
			    {% endfor %}
			</select>
		    </td>
		    <td>Municipio</td>
		    <td>
			<select id="id_cod_municipio" name="municipio" required=True style='width: 200px;'>
			    <option value="">---------</option>
				{% for m in list_mun %}
				    {% if m.pk == obj_reg_cen.id_mun%}
					<option value='{{m.cod_municipio}}' selected='selected'>{{m.municipio}}</option>
				    {% endif %}
				    {% if not m.pk == obj_reg_cen.id_mun%}
					<option value='{{m.cod_municipio}}'>{{m.municipio}}</option>
				    {% endif %}
				{% endfor %}
			</select>
		    </td>
		    <td>Parroquia</td>
		    <td>
			<select id="id_cod_parroquia" name="parroquia" required=True style='width: 200px;'>
			    <option value="">---------</option>
				{% for p in list_par %}
				    {% if p.cod_parroquia == obj_reg_cen.parroquia%}
					<option value='{{p.cod_parroquia}}' selected='selected'>{{p.parroquia}}</option>
				    {% endif %}
				    {% if not p.cod_parroquia == obj_reg_cen.parroquia%}
					<option value='{{p.cod_parroquia}}'>{{p.parroquia}}</option>
				    {% endif %}
				{% endfor %}
			</select>
		    </td>
		    </tr>
		    <tr>
			<td>Codigo centro</td>
			<td>
			    <input id="id_cod_n" maxlength="11" name="cod_n" required=True type="number" value='{{obj_reg_cen.cod_n}}'/>
			    <input id="id_mun" maxlength="11" name="id_mun" type="hidden" value='{{obj_reg_cen.id_mun}}'/>
			</td>
			<td>Codigo centro viejo</td>
			<td>
			    <input id="id_cod_v" maxlength="11" name="cod_v" required=True type="number" value='{{obj_reg_cen.cod_v}}'/>
			</td>
		    </tr>
		    <tr>
			<td colspan='6' style='background-color: #D9EDF7'>Centro de votación</td>
		    </tr>
		    <tr>
			<td colspan='6'>
			    <textarea cols="135" id="id_c_votacion" maxlength="1500" name="c_votacion" rows="10" required=True>{{obj_reg_cen.c_votacion}}</textarea>
			</td>
		    </tr>
		    <tr>
			<td colspan='6' style='background-color: #D9EDF7'>Dirección</td>
		    </tr>
		    <tr>
			<td colspan='6'>
			    <textarea cols="135" id="id_direccion" maxlength="1500" name="direccion" rows="10" required=True>{{obj_reg_cen.direccion}}</textarea>
			</td>
		    </tr>
		    <tr>
			<td><input type="submit" value="Actualizar"/></td>
		    </tr>
	    </table>
	</form>
    {% endblock contenido%}

templates/centro_votacion/centro_votacion.html
{% extends "base/base.html" %} <!-- Bloque, Plantilla base -->
    {% block title %}Registrar Centro de Votación{% endblock %}
    
    {% block extra_head %}
	<script src="{{STATIC_URL}}js/jquery-1.11.2.min.js"></script>
    {% endblock extra_head %}
    
    {% block contenido %}
	<form method="post">
	    {% csrf_token %}
	    {{form.as_p}}
	    <input type="submit" value="Registrar"/>
	</form>
    <a href='/centro_votacion/data'>
	<button>Exportar Centros</button>
    </a>
    {% endblock contenido%}

templates/centro_votacion/eliminar_centro_votacion.html
{% extends "base/base.html" %} <!-- Bloque, Plantilla base -->
    {% block title %}Eliminar Parroquia{% endblock %}
    
    {% block contenido %}
	<form method="post">{% csrf_token %}
		¿ Esta seguro que desea eliminar el registro "{{ object }}"?
		<input type="submit" value="Eliminar" />
	</form>
	{% endblock contenido%}

templates/centro_votacion/lista_centro_votacion.html
{% extends "base/base.html" %} <!-- Heredando (Bloque) plantilla index -->
	{% block title %}Lista de Centros{% endblock title%}
	{% if form.non_field_errors %}
	<div class="panel">
	  {{ form.non_field_errors }}
	</div>
	{% endif %}

	{% block contenido %}
	<!-- ************************************************************* -->
	    <table style='width:80em;'>
	      <tr>
		<td colspan=3>
		  <a href='/centro_votacion/data'>
		  	{% if user.username == "admin" %}
				<button>Importar Centros</button>
			{% endif %}
    	  </a>
		</td>
	      </tr>
	      <tr>
	      <td style='text-align: left' colspan='7'>
		  <a href="/centro_votacion/registrar_centro" title='Nuevo'>  
		    Registrar Centro
		  </a>
		</td>
	      </tr>
	      <tr style='background-color: #D9EDF7;text-align: center;'>
	    <td width='10px;'>Item</td>
		<td width="150px;">Estado</td>
		<td>Municipio</td>
		<td>Parroquia</td>
		<td>Código</td>
		<td>Centro Votación</td>
		<td colspan=3>Acción</td>
	      </tr>
	      {% for c in list_centro_votacion %}
	      <tr style='text-align: center;' class="{% cycle 'impar' 'par' %}">
	    <td>{{c.id}}</td>
		<td>{{ c.estado }}</td>
		<td>
			{% for m in municipio %}
				{% if m.cod_municipio == c.id_mun %}
					{{m.municipio}}
				{% endif %}
			{% endfor %}
		</td>
		<td>

			{% for p in parroquia %}
				{% if  p.estado_id == c.estado_id  and p.municipio == c.id_mun and p.cod_parroquia == c.parroquia%}
					{{p.parroquia}}
				{% endif %}
			{% endfor %}

		</td>
		<td>{{c.cod_n}}</td>
		<td>{{ c.c_votacion }}</td>
		<td>
		  <a href='{% url 'actualizar_centro' c.id %}'>
		    <img src='../../static/admin/img/icon_changelink.gif' title='Editar'>
		  </a>
		</td>
		<td>
		  <a onclick="eliminar_data('{{c.id}}','/centro_votacion/eliminar_centro/')">
		    <img src='../../static/admin/img/icon_deletelink.gif' title='Eliminar'></td>
		  </a>
	      </tr>
	      {% empty %}
	      <tr style='text-align: center;'>
		<td colspan=2>No se encuentran registros</td>
	      </tr>
	      {% endfor %}
	    </table>
	    <div class="pagination" style='margin-left: 15em;'>
	    <span class="step-links">
	      {% if list_centro_votacion.has_previous %}
		<a href="?page={{ list_centro_votacion.previous_page_number }}">Anterior</a>
	      {% endif %}
	    <span class="current">
	      Página {{ list_centro_votacion.number }} de {{ list_centro_votacion.paginator.num_pages }}.
	    </span>
	    {% if list_centro_votacion.has_next %}
	      <a href="?page={{ list_centro_votacion.next_page_number }}">Siguiente</a>
	    {% endif %}
	    </span>
	    </div>
	{% endblock contenido%}
	<!-- ************************************************************* -->

templates/centro_votacion/registrar_centro_votacion.html
{% extends "base/base.html" %} <!-- Bloque, Plantilla base -->
    {% block title %}Registrar Centro de Votación{% endblock %}
    
    {% block contenido %}
	<form method="post">
	    {% csrf_token %}
	    <table>
		<tr>
		    <td colspan='6' style='background-color: #D9EDF7'>Registrar Centro Votación</td>
		</tr>
		<tr>
		    <td>Estado</td>
		    <td>
			<select id="id_cod_estado" name="estado" required=True style='width: 200px;'>
			    <option value="">-----------------------------</option>
			    {% for e in list_estado %}
				<option value='{{e.cod_estado}}'>{{ e.estado }}</option>
			    {% endfor %}
			</select>
		    </td>
		    <td>Municipio</td>
		    <td>
			<select id="id_cod_municipio" name="municipio" required=True style='width: 200px;'>
			    <option value="" selected="selected">----------------------------</option>
			</select>
		    </td>
		    <td>Parroquia</td>
		    <td>
			<select id="id_cod_parroquia" name="parroquia" required=True style='width: 200px;'>
			    <option value="" selected="selected">---------------------</option>
			</select>
		    </td>
		    </tr>
		    <tr>
			<td>Codigo centro</td>
			<td>
			    <input id="id_cod_n" maxlength="11" name="cod_n" type="number" required=True />
			    <input id="id_mun" maxlength="11" name="id_mun" type="hidden" />
			</td>
			<td>Codigo centro viejo</td>
			<td>
			    <input id="id_cod_v" maxlength="11" name="cod_v" type="number" required=True/>
			</td>
		    </tr>
		    <tr>
			<td colspan='6' style='background-color: #D9EDF7'>Centro de votación</td>
		    </tr>
		    <tr>
			<td colspan='6'>
			    <textarea cols="135" id="id_c_votacion" maxlength="1500" name="c_votacion" rows="10" required=True></textarea>
			</td>
		    </tr>
		    <tr>
			<td colspan='6' style='background-color: #D9EDF7'>Dirección</td>
		    </tr>
		    <tr>
			<td colspan='6'><textarea cols="135" id="id_direccion" maxlength="1500" name="direccion" rows="10" required=True></textarea></td>
		    </tr>
		    <tr>
			<td><input type="submit" value="Registrar"/></td>
		    </tr>
	    </table>
	</form>
    {% endblock contenido%}